// Font Libraries
import { Geist, Geist_Mono } from "next/font/google";

// Global Styles
import "./globals.css";

// Next.js Types
import type { Metadata } from "next";

// UI Components
import Header from "@/layouts/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "English Shortcut",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen min-w-full bg-yellow-200`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
